apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: influxdb-ingress
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/influxdb`)
      kind: Rule
      services:
        - name: influxdb-service
          port: 8086
      middlewares:
        - name: influxdb-stripprefix
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: influxdb-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /influxdb