kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: influxdb-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: influxdb-service
                port:
                  number: 8086