apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot-deployment
  namespace: production
  labels:
    app: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
        - image: server01-ubuntu:32000/discord-bot-image:latest
          name: discord-bot
          envFrom:
            - configMapRef:
                name: discord-bot-config
            - secretRef:
                name: discord-bot-secrets
