apiVersion: v1
kind: Service
metadata:
  name: minecraft-controller-service
  namespace: production

spec:
  selector:
    app: minecraft-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  
