apiVersion: v1
kind: Service
metadata:
  name: docker-registry-service
  namespace: production

spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: docker-registry
