apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: docker-registry-ingress
  namespace: production

spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: docker-registry-service
          port: 5000
          namespace: production
      middlewares:
        - name: docker-registry-stripprefix
  tls:
    secretName: docker-registry-secrets
