apiVersion: v1
kind: Service
metadata:
  name: minecraft-2022-service
  namespace: production

spec:
  type: NodePort
  selector:
    app: minecraft-2022
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-2022-rcon-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: minecraft-2022
  ports:
    - protocol: TCP
      port: 30003
      targetPort: 25575
      nodePort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-2022-query-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: minecraft-2022
  ports:
    - protocol: UDP
      port: 30002
      targetPort: 25566
      nodePort: 30002
