apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-2022-config
  namespace: production

data:
  EULA: "TRUE"
  SERVER_NAME: "Kubernetes Server"
  MOTD: "Welcome to our Minecraft Server!"
  DIFFICULTY: "normal"
  MODE: "survival"
  SNOOPER_ENABLED: "false"
  ENABLE_RCON: "true"
  RCON_PORT: "25575"
  ENABLE_QUERY: "true"
  QUERY_PORT: "25566"
